export default {
  login: "Verysatisfied",
  id: 93960671,
  node_id: "U_kgDOBZm53w",
  avatar_url: "https://avatars.githubusercontent.com/u/93960671?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Verysatisfied",
  html_url: "https://github.com/Verysatisfied",
  followers_url: "https://api.github.com/users/Verysatisfied/followers",
  following_url:
    "https://api.github.com/users/Verysatisfied/following{/other_user}",
  gists_url: "https://api.github.com/users/Verysatisfied/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Verysatisfied/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Verysatisfied/subscriptions",
  organizations_url: "https://api.github.com/users/Verysatisfied/orgs",
  repos_url: "https://api.github.com/users/Verysatisfied/repos",
  events_url: "https://api.github.com/users/Verysatisfied/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Verysatisfied/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 14,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2021-11-09T02:51:16Z",
  updated_at: "2023-08-27T09:24:12Z",
};
